apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umbrella-stack
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: stack
    repoURL: $(REPO_URL)
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - Validate=false
    automated:
      prune: true
      selfHeal: true
